### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by MaggiWuerze** [sbang/ansmtpserver#1]
Maven install fails, even adding the dependency manually did not help:

Exception in thread "Thread-3" java.lang.NoClassDefFoundError: com/google/common/collect/EmptyImmutableList$1
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:68)
	at com.google.common.collect.ImmutableList.copyFromCollection(ImmutableList.java:294)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:260)
	at ru.concerteza.util.concurrency.CallableList.call(CallableList.java:45)
	at ru.concerteza.util.concurrency.CallableList.call(CallableList.java:19)
	at ru.concerteza.util.concurrency.CtzConcurrencyUtils$CallableWrapper.run(CtzConcurrencyUtils.java:35)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.EmptyImmutableList$1
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more

**Comment by sbang** [comment]
What system did you try building on? What versions of java, maven etc. did you use? What command did you try building it with?

I just cloned the project and built it (debian 9.6 "stretch", amd64, openjdk-8 8u181-b13-2~deb9u1, maven 3.3.9-4) with "mvn clean install" and it built without any issues:
 ```
[INFO] Installing /home/sb/workspaces/ws01/ansmtpserver/target/ansmtpserver-0.0.1-SNAPSHOT-installer.zip to /home/sb/.m2/repository/ansmtpserver/ansmtpserver/0.0.1-SNAPSHOT/ansmtpserver-0.0.1-SNAPSHOT-installer.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.302 s
[INFO] Finished at: 2019-01-06T19:41:08+01:00
[INFO] Final Memory: 21M/307M
[INFO] ------------------------------------------------------------------------
sb@lorenzo:~/workspaces/ws01/ansmtpserver$
 ```
